name = "Catalyst CC"
author = "minecraftbossdj & NullHarp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6306b31d1e3a99c1a936e1d45f118be02d414289fc1cf04380a2f084719342a9"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
