name = "Catalyst CC"
author = "minecraftbossdj & NullHarp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c649b9d3805cb44e1074fb1dcda7b7d5f36eb1f9f7b2b259358a6b4df2926a68"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
